baseURL = "http://localhost"
languageCode = "fr"
title = "${Renautech}"
theme = "hugo-coder"

defaultContentLanguage = "fr"

[languages.fr]
weight = 1
languageName = "français"

[[languages.fr.menu.main]]
  name = "Activité"
  weight = 1
  url = "posts/company/activity"
[[languages.fr.menu.main]]
  name = "Expérience"
  weight = 1
  url = "posts/company/experience"
[[languages.fr.menu.main]]
  name = "Inspiration"
  weight = 1
  url = "posts/company/inspiration"
[[languages.fr.menu.main]]
  name = "Les Jardins Connectés"
  weight = 1
  url = "posts/portfolio/jardinsconnectes"
[[languages.fr.menu.main]]
  name = "Glossaire"
  weight = 2
  url = "posts/glossary"

[languages.en]
weight = 2
languageName = "English"
[[languages.en.menu.main]]
  name = "Activity"
  weight = 1
  url = "posts/company/activity"
[[languages.en.menu.main]]
  name = "Experience"
  weight = 1
  url = "posts/company/experience"
[[languages.en.menu.main]]
  name = "Inspiration"
  weight = 1
  url = "posts/company/inspiration"
[[languages.en.menu.main]]
  name = "Connected Gardens"
  weight = 1
  url = "posts/portfolio/jardinsconnectes"
[[languages.en.menu.main]]
  name = "Glossary"
  weight = 2
  url = "posts/glossary"



[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/renaudlamarre/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/renautech/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/renautech/"
[[params.social]]
  name="Email"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url="mailto:renautech.fr@gmail.com"

  paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Renaud Lamarre"
  info = "Full Stack Web developer and IT Senior Project Manager"
  description = "Renautech website"
  keywords = "fullstack developer, project manager, chef de projet, javascript, react, nodejs, web application, website"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2020

  enableTwemoji = true

  colorsheme = "auto"
  hidecolorschemetoggle = false

