baseURL = "http://localhost"
languageCode = "en-us"
title = "${Renautech}"
theme = "hugo-coder"

# Menu links
#[[menu.main]]
#  name = "Mes articles"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "Activité"
  weight = 1
  url = "posts/company/activity"
[[menu.main]]
  name = "Expérience"
  weight = 1
  url = "posts/company/experience"
[[menu.main]]
  name = "Inspiration"
  weight = 1
  url = "posts/company/inspiration"
[[menu.main]]
  name = "Les Jardins Connectés"
  weight = 1
  url = "posts/portfolio/jardinsconnectes"
[[menu.main]]
  name = "Glossaire"
  weight = 2
  url = "posts/glossary"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/renaudlamarre/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/renautech/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/renautech/"
[[params.social]]
  name="Email"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url="mailto:renautech.fr@gmail.com"

  paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Renaud Lamarre"
  info = "Développeur Full Stack JS et IT Senior Project Manager"
  description = "Renautech website"
  keywords = "développeur fullstack, chef de projet, javascript, react, nodejs, application web, site web"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2020

  enableTwemoji = true

  colorsheme = "auto"
  hidecolorschemetoggle = false

