baseURL = "http://localhost"
languageCode = "en-us"
title = "${Renautech}"
theme = "hugo-coder"

# Menu links
[[menu.main]]
  name = "Mes articles"
  weight = 1
  url  = "posts/"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/renautech/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/renautech/"

  paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Renaud Lamarre"
  info = "Développeur Full Stack JS et IT Senior Project Manager"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  footercontent = "Site de présentations et de démonstrations"
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2020

  enableTwemoji = true

  colorsheme = "auto"
  hidecolorschemetoggle = false

